### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hernanif1** [simplyhealth/npm-audit-check#13]
After choosing the option remind me in 24h sometimes I receive the error:
TypeError: Cannot read property 'length' of undefined

But if I run again it works.

**Comment by ChrisChalke** [comment]
Hi @hernanif1 npm-audit-check doesn't have a remind me in 24h option. Did you mean this package https://www.npmjs.com/package/npm-audit-resolver?activeTab=readme instead?

**Comment by hernanif1** [comment]
Wow.. Sorry you are right, I will put it there. Thanks!

**Comment by hernanif1** [comment]
Could you close this issue please?

**Comment by ChrisChalke** [comment]
Closing because it was raised on the wrong package
